from django.utils import timezone


__all__ = [
    "QPAY_MAX_TRADER_ACTIVE_DEPOSIT_TRANSACTIONS",
    "QPAY_MAX_TRADER_ACTIVE_WITHDRAWAL_TRANSACTIONS",
    "QPAY_PROCESS_TRANSACTION_TASK_DELAY",
    "QPAY_API_REQUEST_TIME_TIMEOUT",
]


QPAY_MAX_TRADER_ACTIVE_DEPOSIT_TRANSACTIONS = 5

QPAY_MAX_TRADER_ACTIVE_WITHDRAWAL_TRANSACTIONS = 5


# Delay in seconds
QPAY_PROCESS_TRANSACTION_TASK_DELAY = 60


QPAY_API_REQUEST_TIME_TIMEOUT = timezone.timedelta(seconds=30)
