version: "3.9"

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data:
