# Generated by Django 4.2.7 on 2024-02-13 16:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'trader'), (2, 'merchant'), (3, 'admin')])),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('last_seen', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_light_theme', models.BooleanField(default=True)),
                ('language', models.PositiveSmallIntegerField(choices=[(1, 'english'), (2, 'russian'), (3, 'ukrainian')], default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('otp_base32', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.ImageField(unique=True, upload_to='bank_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('card_number', models.CharField(max_length=19, unique=True)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('use_automation', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weekly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_daily_turnover', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('start_weekly_turnover', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('start_monthly_turnover', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('ad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bank_details', to='main.ad')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bank')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trader', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(editable=False, max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'input'), (2, 'output')], db_index=True, editable=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'rejected'), (2, 'pending'), (3, 'cancelled'), (4, 'reviewing'), (5, 'disputing'), (6, 'completed'), (7, 'failed'), (8, 'refund'), (9, 'partially_paid')], default=2)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('amount_debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.PositiveSmallIntegerField(editable=False)),
                ('currency', models.PositiveSmallIntegerField(choices=[(1, 'uah')], default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lifetime', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('client_card_number', models.CharField(blank=True, max_length=19, null=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_ip', models.GenericIPAddressField()),
                ('merchant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_payments', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='trader_payments', to=settings.AUTH_USER_MODEL)),
                ('trader_bank_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.bankdetails')),
            ],
        ),
        migrations.CreateModel(
            name='TraderDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'requested'), (2, 'pending'), (3, 'completed'), (4, 'failed')], default=1)),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_card_number', models.CharField(max_length=19)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('client_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bank')),
                ('payment', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='main.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PrevPaymentTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.payment')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'rejected'), (2, 'pending'), (3, 'cancelled'), (4, 'reviewing'), (5, 'disputing'), (6, 'completed'), (7, 'failed'), (8, 'refund'), (9, 'partially_paid')])),
                ('amount_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='main.payment')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('wallet_address', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'completed'), (3, 'declined')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantIntegrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_url', models.CharField(max_length=255, unique=True)),
                ('callback_url', models.CharField(max_length=255, unique=True)),
                ('public_key', models.CharField(max_length=255, unique=True)),
                ('private_key', models.CharField(max_length=255)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_reason', models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Payment'), (4, 'Correction')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet_address', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bank'),
        ),
        migrations.AddField(
            model_name='ad',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('trader', 'bank')},
        ),
    ]
