# Generated by Django 4.2.7 on 2024-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_update_at_balance_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
