# Generated by Django 4.2.10 on 2024-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastfetchedtrontransaction',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lastfetchedtrontransaction',
            name='note',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastfetchedtrontransaction',
            name='value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastfetchedtrontransaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
