# Generated by Django 4.2.10 on 2024-03-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_lastfetchedtrontransaction_fetched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastfetchedtrontransaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
