# Generated by Django 4.2.10 on 2024-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_alter_lastfetchedtrontransaction_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastfetchedtrontransaction',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
