# Generated by Django 4.2.10 on 2024-04-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_alter_lastfetchedtrontransaction_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastfetchedtrontransaction',
            options={'ordering': ('-timestamp',)},
        ),
    ]
