# Generated by Django 4.2.7 on 2024-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_start_daily_turnover_bankdetails_current_daily_turnover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='current_daily_turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='current_monthly_turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='current_weekly_turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='weekly_limit',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=12),
            preserve_default=False,
        ),
    ]
