# Generated by Django 4.2.7 on 2024-02-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_balancehistory_delete_servicebalance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
