# Generated by Django 4.2.10 on 2024-03-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_transaction_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_base32',
            new_name='totp_base32',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
