# Generated by Django 4.2.10 on 2024-03-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_otp_base32_user_totp_base32_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_completed',
        ),
        migrations.AddField(
            model_name='user',
            name='tg_username',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
