# Generated by Django 4.2.10 on 2024-03-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_user_signup_completed_user_tg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
