# Generated by Django 4.2.10 on 2024-03-17 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_user_tg_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
