# Generated by Django 4.2.10 on 2024-04-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_ad_options_alter_bankdetails_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraderDeposit',
        ),
    ]
