# Generated by Django 4.2.10 on 2024-04-04 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_user_deposit_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deposit_note',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
