# Generated by Django 4.2.7 on 2023-11-29 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'TRADER'), (2, 'MERCHANT'), (3, 'ADMIN')], editable=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('tz_offset_minutes', models.SmallIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_light_theme', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputTransaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trader_usdt_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exchange_usdt_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('automation_used', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'PENDING_CLIENT_CONFIRMATION'), (2, 'PENDING_TRADER_CONFIRMATION'), (3, 'AUTO_COMPLETED'), (4, 'MANUALLY_COMPLETED'), (5, 'EXPIRED'), (6, 'CANCELLED'), (7, 'DISPUTED')], default=1)),
                ('claimed_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=9)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutputTransaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trader_usdt_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exchange_usdt_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('automation_used', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'PENDING_TRADER_CONFIRMATION'), (2, 'CONFIRMED'), (3, 'FINISHED'), (4, 'EXPIRED'), (5, 'CANCELLED'), (6, 'DISPUTED')], default=1)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=9)),
                ('card_number', models.CharField(editable=False, max_length=19)),
                ('receipt_url', models.CharField(default='', max_length=255, unique=True)),
                ('bank_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bank')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet_address', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'REJECTED'), (3, 'COMPLETED')], default=1)),
                ('wallet_address', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('card_number', models.CharField(max_length=19, unique=True)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('automation_used', models.BooleanField(default=False)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weekly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_turnover', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('weekly_turnover', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('monthly_turnover', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bank')),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrevOutputTransactionTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.outputtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='PrevInputTransactionTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.inputtransaction')),
            ],
        ),
        migrations.AddField(
            model_name='outputtransaction',
            name='requisites_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.requisites'),
        ),
        migrations.AddField(
            model_name='outputtransaction',
            name='trader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MerchantIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(max_length=255, unique=True)),
                ('success_url', models.CharField(max_length=255, unique=True)),
                ('failed_url', models.CharField(max_length=255, unique=True)),
                ('callback_url', models.CharField(max_length=255, unique=True)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inputtransaction',
            name='requisites_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.requisites'),
        ),
        migrations.AddField(
            model_name='inputtransaction',
            name='trader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('trader_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trader_usdt_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exchange_usdt_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('requisites_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.requisites')),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
