# Generated by Django 4.2.7 on 2024-02-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='start_daily_turnover',
            new_name='current_daily_turnover',
        ),
        migrations.RenameField(
            model_name='bankdetails',
            old_name='start_monthly_turnover',
            new_name='current_monthly_turnover',
        ),
        migrations.RenameField(
            model_name='bankdetails',
            old_name='start_weekly_turnover',
            new_name='current_weekly_turnover',
        ),
    ]
