# Generated by Django 4.2.7 on 2024-02-11 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_reason', models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Transaction'), (4, 'Correction')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('card_number', models.CharField(max_length=19, unique=True)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('use_automation', models.BooleanField(default=False)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weekly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_daily_turnover', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True)),
                ('start_weekly_turnover', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True)),
                ('start_monthly_turnover', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=12, null=True)),
                ('ad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bank_details', to='main.ad')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bank')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('wallet_address', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Declined')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraderDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Input'), (2, 'Output')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Disputed'), (4, 'Expired'), (5, 'Cancelled'), (6, 'CHECKING')], default=1)),
                ('claimed_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=9)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('trader_fee', models.PositiveSmallIntegerField()),
                ('admin_fee', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_time', models.DateTimeField()),
                ('client_card_number', models.CharField(blank=True, max_length=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.PositiveSmallIntegerField(choices=[(1, 'Batch'), (2, 'Individual')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Processing'), (2, 'Completed'), (3, 'Failed')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Withdraw',
            new_name='AdminWithdrawal',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='inputtransaction',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='inputtransaction',
            name='requisites',
        ),
        migrations.RemoveField(
            model_name='inputtransaction',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='outputtransaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='outputtransaction',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='outputtransaction',
            name='requisites',
        ),
        migrations.RemoveField(
            model_name='outputtransaction',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='requisites',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='merchant',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_activated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tz_offset_minutes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'English'), (2, 'Russian'), (3, 'Ukrainian')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TRADER'), (2, 'MERCHANT'), (3, 'ADMIN')]),
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Requisites',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='main.transactionrequest'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trader_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trader_bank_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.bankdetails'),
        ),
        migrations.AddField(
            model_name='traderdeposit',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantwithdrawal',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantwithdrawal',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.transaction'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='previnputtransactiontrader',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.transaction'),
        ),
        migrations.AlterField(
            model_name='prevoutputtransactiontrader',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.transaction'),
        ),
        migrations.DeleteModel(
            name='InputTransaction',
        ),
        migrations.DeleteModel(
            name='OutputTransaction',
        ),
        migrations.AlterUniqueTogether(
            name='bankdetails',
            unique_together={('trader', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='ad',
            unique_together={('trader', 'bank')},
        ),
    ]
