# Generated by Django 4.2.7 on 2023-11-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AddField(
            model_name='language',
            name='language_id',
            field=models.SmallIntegerField(db_column='id', default=1, editable=False, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
