# Generated by Django 4.2.7 on 2023-12-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_language_id_language_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(default=3453498, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
