# Generated by Django 4.2.7 on 2023-12-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_otp_base32_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='is_active',
            new_name='is_activated',
        ),
        migrations.RenameField(
            model_name='requisites',
            old_name='is_active',
            new_name='is_activated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='is_activated',
        ),
    ]
