# Generated by Django 4.2.7 on 2024-02-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bankdetails_is_deleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrevInputTransactionTrader',
            new_name='PrevTransactionTrader',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.DeleteModel(
            name='PrevOutputTransactionTrader',
        ),
    ]
