# Generated by Django 4.2.7 on 2024-02-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_previnputtransactiontrader_prevtransactiontrader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'input'), (2, 'output')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchantwithdrawal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'completed'), (3, 'declined')], default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'completed'), (3, 'disputed'), (4, 'expired'), (5, 'cancelled'), (6, 'checking')], default=1),
        ),
        migrations.AlterField(
            model_name='transactionrequest',
            name='request_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'batch'), (2, 'individual')]),
        ),
        migrations.AlterField(
            model_name='transactionrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'processing'), (2, 'completed'), (3, 'failed')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'english'), (2, 'russian'), (3, 'ukrainian')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'trader'), (2, 'merchant'), (3, 'admin')]),
        ),
    ]
