# Generated by Django 4.2.7 on 2024-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_payment_amount_alter_payment_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='use_automation',
            field=models.BooleanField(default=False),
        ),
    ]
