# Generated by Django 4.2.7 on 2024-02-15 11:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_payment_receipt_url_payment_use_automation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Transaction'
        ),
        migrations.RenameModel(
            old_name='PaymentStatusHistory',
            new_name='TransactionStatusHistory'
        ),
        migrations.RenameModel(
            old_name='PrevPaymentTrader',
            new_name='PrevTransactionTrader',
        ),
        migrations.RenameField(
            model_name='traderdeposit',
            old_name='blockchain_transaction_id',
            new_name='blockchain_transaction',
        ),
        migrations.RenameField(
            model_name='balancehistory',
            old_name='payment',
            new_name='transaction'
        ),
        migrations.RenameField(
            model_name='prevtransactiontrader',
            old_name='payment',
            new_name='transaction'
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='payment',
            new_name='transaction'
        ),
        migrations.AlterField(
            model_name='balancehistory',
            name='change_reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Disputed'), (4, 'Correction')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='icon_url',
            field=models.URLField(max_length=1024, unique=True),
        ),
    ]
