# Generated by Django 4.2.7 on 2024-02-17 11:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_servicebalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_reason', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Correction'), (2, 'Commission'), (3, 'Reserved to Refund'), (4, 'Release after Refund'), (5, 'Freeze for transaction'), (6, 'Release for transaction'), (7, 'Return penalty'), (8, 'Take away for transaction'), (9, 'Give away for transaction')])),
                ('change_active_balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('change_frozen_balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('new_frozen_balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('new_active_balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceBalance',
        ),
        migrations.AlterField(
            model_name='balance',
            name='active_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='balance',
            name='frozen_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
